=== Calepa/CERS3/Main/Data/XML Schemas/RegulatorFacilityCreate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:cers="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityCreate/1/06/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityCreate/1/06/">
	<xs:element name="RegulatorFacilityCreate" type="cers:RegulatorFacilityCreateType"/>
	<xs:complexType name="RegulatorFacilityCreateType">
		<xs:sequence>
			<xs:element name="RegulatorTransactionKey" type="cers:RegulatorKeyType" nillable="false">
				<xs:annotation>
					<xs:documentation>20.0003</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:choice minOccurs="0">
				<xs:element name="OrganizationCode">
					<xs:annotation>
						<xs:documentation>20.0015</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:positiveInteger">
							<xs:totalDigits value="9"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:sequence>
					<xs:element name="OrganizationName">
						<xs:annotation>
							<xs:documentation>20.0016</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="100"/>
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="OrganizationHeadquarters" minOccurs="0">
						<xs:annotation>
							<xs:documentation>20.0106</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="75"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:choice>
			<xs:element name="FacilityID" minOccurs="0">
				<xs:annotation>
					<xs:documentation>1</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FacilityRegulatorKey" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0084</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="36"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="EPAID" minOccurs="0">
				<xs:annotation>
					<xs:documentation>2</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FacilityName">
				<xs:annotation>
					<xs:documentation>3</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="70"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FacilityAddress" type="cers:FacilityAddressType"/>
			<xs:element name="SubmittalElements" type="cers:SubmittalElementsType" minOccurs="0"/>
			<xs:element name="GeographicInformation" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="CERSPoint" type="cers:CERSGeographicPointLocationDataType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Comments" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0104  Include any comments that explains why the Regulator is creating an additional/duplicate facility at the same address.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="500"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IgnoreExactDuplicateAddressWarning" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>20.0105</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="mode" use="required">
			<xs:annotation>
				<xs:documentation>20.0107</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Commit"/>
					<xs:enumeration value="Trial"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="OrganizationType"/>
	<xs:complexType name="FacilityAddressType">
		<xs:sequence>
			<xs:element name="SiteAddress">
				<xs:annotation>
					<xs:documentation>103</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="70"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SupplementalAddress" minOccurs="0">
				<xs:annotation>
					<xs:documentation>103a</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="30"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="City">
				<xs:annotation>
					<xs:documentation>104</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ZipCode">
				<xs:annotation>
					<xs:documentation>105</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SubmittalElementType">
		<xs:attribute name="regulatorCode" type="xs:positiveInteger" use="optional">
			<xs:annotation>
				<xs:documentation>20.0001</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reportingRequirement" type="cers:ReportingRequirementType" use="optional">
			<xs:annotation>
				<xs:documentation>20.0088</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="nextDueDate" type="cers:Date" use="optional">
			<xs:annotation>
				<xs:documentation>20.0087</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="SubmittalElementsType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="FacilityInformation">
				<xs:complexType>
					<xs:attribute name="nextDueDate" type="cers:Date" use="optional">
						<xs:annotation>
							<xs:documentation>20.0087</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="HazardousMaterialsInventory" type="cers:SubmittalElementType"/>
			<xs:element name="EmergencyResponseTrainingPlans" type="cers:SubmittalElementType"/>
			<xs:element name="UndergroundStorageTanks" type="cers:SubmittalElementType"/>
			<xs:element name="OnsiteHazardousWasteTreatmentNotification" type="cers:SubmittalElementType"/>
			<xs:element name="RecyclableMaterialsReport" type="cers:SubmittalElementType"/>
			<xs:element name="RemoteWasteConsolidationsAnnualNotification" type="cers:SubmittalElementType"/>
			<xs:element name="HWTankClosureCertification" type="cers:SubmittalElementType"/>
			<xs:element name="AbovegroundPetroleumStorageTanks" type="cers:SubmittalElementType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="CERSGeographicPointLocationDataType">
		<xs:sequence>
			<xs:element name="LatitudeMeasure" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0001</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="4"/>
						<xs:maxLength value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LongitudeMeasure" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0002</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="4"/>
						<xs:maxLength value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HorizontalAccuracyMeasure" type="xs:decimal" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0003</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="HorizontalCollectionMethod">
				<xs:annotation>
					<xs:documentation>21.0004</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:enumeration value="101"/>
						<xs:enumeration value="103"/>
						<xs:enumeration value="104"/>
						<xs:enumeration value="107"/>
						<xs:enumeration value="108"/>
						<xs:enumeration value="109"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GeographicReferencePoint">
				<xs:annotation>
					<xs:documentation>21.0005</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:enumeration value="101"/>
						<xs:enumeration value="102"/>
						<xs:enumeration value="103"/>
						<xs:enumeration value="108"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HorizontalReferenceDatum">
				<xs:annotation>
					<xs:documentation>21.0006</xs:documentation>
					<xs:documentation>Typical value is WGS84</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NAD27"/>
						<xs:enumeration value="NAD83"/>
						<xs:enumeration value="WGS84"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DataCollectionDate" nillable="false" minOccurs="0">
				<xs:annotation>
					<xs:documentation>21.0007</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:date"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="RegulatorKeyType">
		<xs:restriction base="cers:GUID"/>
	</xs:simpleType>
	<xs:simpleType name="GUID">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})|(\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OrganizationCodeType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="100000001"/>
			<xs:maxInclusive value="999999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateTime">
		<xs:restriction base="xs:dateTime">
			<xs:minInclusive value="1985-01-01T00:00:00Z"/>
			<xs:maxInclusive value="2024-12-31T23:59:59Z"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Date">
		<xs:restriction base="xs:date">
			<xs:minInclusive value="1985-01-01"/>
			<xs:maxInclusive value="2024-12-31"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReportingRequirementType">
		<xs:restriction base="xs:int">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Calepa/CERS3/Main/Data/XML Schemas/TestData/CreateFacility-1455 - v106.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 sp1 (x64) (http://www.altova.com)-->
<cers:RegulatorFacilityCreate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cers="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityCreate/1/06/" mode="Commit" xsi:schemaLocation="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityCreate/1/06/ http://cersservices.calepa.ca.gov/Schemas/1/06/RegulatorFacilityCreate.xsd">
	<RegulatorTransactionKey>D49066C4-27F4-4630-947A-A775259B9790</RegulatorTransactionKey>
	<FacilityName>Mike's House</FacilityName>
	<FacilityAddress>
		<SiteAddress>1455 Stoney Cross Ln</SiteAddress>
		<City>Lincoln</City>
		<ZipCode>95648</ZipCode>
	</FacilityAddress>
	<IgnoreExactDuplicateAddressWarning>true</IgnoreExactDuplicateAddressWarning>
</cers:RegulatorFacilityCreate>

=== Calepa/CERS3/Main/Data/XML Schemas/TestData/CreateFacility - 1001 Sac - v106 ignoredupwarning-true.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 sp1 (x64) (http://www.altova.com)-->
<cers:RegulatorFacilityCreate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cers="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityCreate/1/06/" mode="Commit" xsi:schemaLocation="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityCreate/1/06/ http://cersservices.calepa.ca.gov/Schemas/1/06/RegulatorFacilityCreate.xsd">
	<RegulatorTransactionKey>D49066C4-27F4-4630-947A-A775259B9790</RegulatorTransactionKey>
	<FacilityName>Cal/EPA Fun Center</FacilityName>
	<FacilityAddress>
		<SiteAddress>1001 I St.</SiteAddress>
		<City>Sacramento</City>
		<ZipCode>95814</ZipCode>
	</FacilityAddress>
	<IgnoreExactDuplicateAddressWarning>true</IgnoreExactDuplicateAddressWarning>
</cers:RegulatorFacilityCreate>
