=== Calepa/CERS3/Main/Data/XML Schemas/RegulatorFacilityQuery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (x64) (http://www.altova.com) by Mike Reagan (Air Resources Board) -->
<!--W3C Schema generated by XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:cers="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityQuery/1/05/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityQuery/1/05/">
	<xs:element name="RegulatorFacilityQuery">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Facility" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="cers:FacilityType"/>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="timeStamp" type="xs:dateTime" use="required"/>
			<xs:attribute name="returnedResultCount" type="xs:int" use="required"/>
			<xs:attribute name="totalQueryResultCount" type="xs:int" use="required"/>
			<xs:attribute name="transactionKey" type="cers:GUID" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FacilityType">
		<xs:sequence>
			<xs:element name="CERSID" type="cers:CERSIDType">
				<xs:annotation>
					<xs:documentation>1a</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="FacilityID" type="xs:string" minOccurs="0"/>
			<xs:element name="FacilityRegulatorKey" type="xs:string" minOccurs="0"/>
			<xs:element name="RegulatorCode" type="xs:int"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="LastSubmittalOn" type="cers:Date" nillable="true" minOccurs="0"/>
			<xs:element name="EstablishedOn" type="cers:Date"/>
			<xs:element name="Organization" type="cers:OrganizationType"/>
			<xs:element name="SubmittalElements" type="cers:SubmittalElementsType"/>
			<xs:element name="FacilityAddress" type="cers:FacilityAddressType" minOccurs="0"/>
			<xs:element name="StandardizedAddress" type="cers:StandardizedAddressType" minOccurs="0"/>
			<xs:element name="GeographicInformation" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="CERSPoint" type="cers:CERSGeographicPointLocationDataType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MessagesType">
		<xs:sequence>
			<xs:element name="Message" type="cers:MessageType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MessageType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Warning"/>
							<xs:enumeration value="Error"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="CERSGeographicPointLocationDataType">
		<xs:sequence>
			<xs:element name="LatitudeMeasure" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0001</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="4"/>
						<xs:maxLength value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LongitudeMeasure" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0002</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="4"/>
						<xs:maxLength value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HorizontalAccuracyMeasure" type="xs:decimal" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0003</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="HorizontalCollectionMethod">
				<xs:annotation>
					<xs:documentation>21.0004</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:enumeration value="101"/>
						<xs:enumeration value="103"/>
						<xs:enumeration value="104"/>
						<xs:enumeration value="107"/>
						<xs:enumeration value="108"/>
						<xs:enumeration value="109"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GeographicReferencePoint">
				<xs:annotation>
					<xs:documentation>21.0005</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:enumeration value="101"/>
						<xs:enumeration value="102"/>
						<xs:enumeration value="103"/>
						<xs:enumeration value="108"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HorizontalReferenceDatum">
				<xs:annotation>
					<xs:documentation>21.0006</xs:documentation>
					<xs:documentation>Typical value is WGS84</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NAD27"/>
						<xs:enumeration value="NAD83"/>
						<xs:enumeration value="WGS84"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DataCollectionDate" nillable="false">
				<xs:annotation>
					<xs:documentation>21.0007</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:date"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SubmittalElementType">
		<xs:attribute name="regulatorCode" type="xs:positiveInteger" use="required">
			<xs:annotation>
				<xs:documentation>20.0001</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reportingRequirement" type="cers:ReportingRequirementType" use="required">
			<xs:annotation>
				<xs:documentation>20.0088</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="nextDueDate" type="cers:Date" use="optional">
			<xs:annotation>
				<xs:documentation>20.0087</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="StandardizedAddressType">
		<xs:sequence>
			<xs:element name="SiteAddress" type="xs:string">
				<xs:annotation>
					<xs:documentation>103</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="City" type="xs:string">
				<xs:annotation>
					<xs:documentation>104</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ZipCode" type="xs:string">
				<xs:annotation>
					<xs:documentation>105</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StreetRange" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0108</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StreetPreDirection" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0109</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StreetName" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0110</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StreetPostDirection" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0111</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StreetSuffix" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0112</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Suite" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="RegulatorKeyType">
		<xs:restriction base="cers:GUID"/>
	</xs:simpleType>
	<xs:simpleType name="GUID">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})|(\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OrganizationCodeType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="10000001"/>
			<xs:maxInclusive value="99999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CERSIDType">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="10000001"/>
			<xs:maxInclusive value="99999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateTime">
		<xs:restriction base="xs:dateTime">
			<xs:minInclusive value="1985-01-01T00:00:00Z"/>
			<xs:maxInclusive value="2024-12-31T23:59:59Z"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Date">
		<xs:restriction base="xs:date">
			<xs:minInclusive value="1985-01-01"/>
			<xs:maxInclusive value="2024-12-31"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReportingRequirementType">
		<xs:restriction base="xs:int">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="OrganizationType">
		<xs:sequence>
			<xs:element name="Code">
				<xs:annotation>
					<xs:documentation>20.0015</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="cers:OrganizationCodeType"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Name" type="xs:string">
				<xs:annotation>
					<xs:documentation>20.0016</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Headquarters" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>20.0106</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="FacilityCount" type="xs:int"/>
			<xs:element name="UserCount" type="xs:int"/>
			<xs:element name="LeadRegulatorCode" type="xs:int"/>
			<xs:element name="LastSubmittalOn" type="cers:Date" minOccurs="0"/>
			<xs:element name="Origin" type="cers:OrganizationOriginType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SubmittalElementsType">
		<xs:sequence>
			<xs:element name="FacilityInformation" type="cers:SubmittalElementType"/>
			<xs:element name="HazardousMaterialsInventory" type="cers:SubmittalElementType"/>
			<xs:element name="EmergencyResponseTrainingPlans" type="cers:SubmittalElementType"/>
			<xs:element name="UndergroundStorageTanks" type="cers:SubmittalElementType"/>
			<xs:element name="OnsiteHazardousWasteTreatmentNotification" type="cers:SubmittalElementType"/>
			<xs:element name="RecyclableMaterialsReport" type="cers:SubmittalElementType"/>
			<xs:element name="RemoteWasteConsolidationsAnnualNotification" type="cers:SubmittalElementType"/>
			<xs:element name="HWTankClosureCertification" type="cers:SubmittalElementType"/>
			<xs:element name="AbovegroundPetroleumStorageTanks" type="cers:SubmittalElementType"/>
			<xs:element name="CaliforniaAccidentalReleasePrevention" type="cers:SubmittalElementType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FacilityAddressType">
		<xs:sequence>
			<xs:element name="SiteAddress" type="xs:string">
				<xs:annotation>
					<xs:documentation>103</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SupplementalAddress" type="xs:string" minOccurs="0"/>
			<xs:element name="City" type="xs:string">
				<xs:annotation>
					<xs:documentation>104</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ZipCode" type="xs:string">
				<xs:annotation>
					<xs:documentation>105</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="OrganizationOriginType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="4"/>
			<xs:enumeration value="5"/>
			<xs:enumeration value="6"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Calepa/CERS3/Main/Data/XML Schemas/TestData/Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 sp1 (x64) (http://www.altova.com)-->
<cers:RegulatorFacilityQuery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cers="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityQuery/1/05/" timeStamp="2001-12-17T09:30:47Z" returnedResultCount="0" totalQueryResultCount="0" transactionKey="00000000-0000-0000-0000-000000000000" xsi:schemaLocation="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityQuery/1/05/ RegulatorFacilityQuery.xsd">
	<Facility>
		<CERSID>10000001</CERSID>
		<FacilityID>String</FacilityID>
		<FacilityRegulatorKey>String</FacilityRegulatorKey>
		<RegulatorCode>0</RegulatorCode>
		<Name>String</Name>
		<LastSubmittalOn>1985-01-01</LastSubmittalOn>
		<EstablishedOn>1985-01-01</EstablishedOn>
		<Organization>
			<Code>10000001</Code>
			<Name>String</Name>
			<Headquarters>String</Headquarters>
			<FacilityCount>0</FacilityCount>
			<UserCount>0</UserCount>
			<LeadRegulatorCode>0</LeadRegulatorCode>
			<LastSubmittalOn>1985-01-01</LastSubmittalOn>
			<Origin>1</Origin>
		</Organization>
		<SubmittalElements>
			<FacilityInformation regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<HazardousMaterialsInventory regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<EmergencyResponseTrainingPlans regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<UndergroundStorageTanks regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<OnsiteHazardousWasteTreatmentNotification regulatorCode="1" reportingRequirement="1" nextDueDate="1985-01-01"/>
			<RecyclableMaterialsReport regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<RemoteWasteConsolidationsAnnualNotification regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<HWTankClosureCertification regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<AbovegroundPetroleumStorageTanks regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<CaliforniaAccidentalReleasePrevention regulatorCode="1" reportingRequirement="1" nextDueDate="1985-01-01"/>
		</SubmittalElements>
		<FacilityAddress>
			<SiteAddress>String</SiteAddress>
			<SupplementalAddress>String</SupplementalAddress>
			<City>String</City>
			<ZipCode>String</ZipCode>
		</FacilityAddress>
		<StandardizedAddress>
			<SiteAddress></SiteAddress>
			<City></City>
			<ZipCode></ZipCode>
		</StandardizedAddress>
		<GeographicInformation>
			<CERSPoint>
				<LatitudeMeasure>aaaa</LatitudeMeasure>
				<LongitudeMeasure>aaaa</LongitudeMeasure>
				<HorizontalAccuracyMeasure>0</HorizontalAccuracyMeasure>
				<HorizontalCollectionMethod>104</HorizontalCollectionMethod>
				<GeographicReferencePoint>101</GeographicReferencePoint>
				<HorizontalReferenceDatum>NAD83</HorizontalReferenceDatum>
				<DataCollectionDate>1957-08-13</DataCollectionDate>
			</CERSPoint>
		</GeographicInformation>
	</Facility>
	<Facility>
		<CERSID>10000001</CERSID>
		<FacilityID>String</FacilityID>
		<FacilityRegulatorKey>String</FacilityRegulatorKey>
		<RegulatorCode>0</RegulatorCode>
		<Name>String</Name>
		<LastSubmittalOn>1985-01-01</LastSubmittalOn>
		<EstablishedOn>1985-01-01</EstablishedOn>
		<Organization>
			<Code>10000001</Code>
			<Name>String</Name>
			<Headquarters>String</Headquarters>
			<FacilityCount>0</FacilityCount>
			<UserCount>0</UserCount>
			<LeadRegulatorCode>0</LeadRegulatorCode>
			<LastSubmittalOn>1985-01-01</LastSubmittalOn>
			<Origin>2</Origin>
		</Organization>
		<SubmittalElements>
			<FacilityInformation regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<HazardousMaterialsInventory regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<EmergencyResponseTrainingPlans regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<UndergroundStorageTanks regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<OnsiteHazardousWasteTreatmentNotification regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<RecyclableMaterialsReport regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<RemoteWasteConsolidationsAnnualNotification regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<HWTankClosureCertification regulatorCode="1" reportingRequirement="2" nextDueDate="1985-01-01"/>
			<AbovegroundPetroleumStorageTanks regulatorCode="1" reportingRequirement="3" nextDueDate="1985-01-01"/>
			<CaliforniaAccidentalReleasePrevention regulatorCode="1" reportingRequirement="1" nextDueDate="1985-01-01"/>
		</SubmittalElements>
		<FacilityAddress>
			<SiteAddress>String</SiteAddress>
			<SupplementalAddress>String</SupplementalAddress>
			<City>String</City>
			<ZipCode>String</ZipCode>
		</FacilityAddress>
		<StandardizedAddress>
			<SiteAddress>String</SiteAddress>
			<City>String</City>
			<ZipCode>String</ZipCode>
			<StreetRange>String</StreetRange>
			<StreetPreDirection>String</StreetPreDirection>
			<StreetName>String</StreetName>
			<StreetPostDirection>String</StreetPostDirection>
			<StreetSuffix>String</StreetSuffix>
			<Suite>String</Suite>
		</StandardizedAddress>
		<GeographicInformation>
			<CERSPoint>
				<LatitudeMeasure>aaaa</LatitudeMeasure>
				<LongitudeMeasure>aaaa</LongitudeMeasure>
				<HorizontalAccuracyMeasure>0</HorizontalAccuracyMeasure>
				<HorizontalCollectionMethod>103</HorizontalCollectionMethod>
				<GeographicReferencePoint>102</GeographicReferencePoint>
				<HorizontalReferenceDatum>WGS84</HorizontalReferenceDatum>
				<DataCollectionDate>1957-08-13</DataCollectionDate>
			</CERSPoint>
		</GeographicInformation>
	</Facility>
</cers:RegulatorFacilityQuery>

=== Calepa/CERS3/Main/Data/XML Schemas/TestData/Test3.xml
<cers:RegulatorFacilityQuery xsi:schemaLocation="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityQuery/1/05/ http://cersservices.calepa.ca.gov/Schemas/1/05/RegulatorFacilityQuery.xsd" xmlns:cers="http://cersservices.calepa.ca.gov/Schemas/RegulatorFacilityQuery/1/05/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" timeStamp="2014-04-14T20:13:55Z" returnedResultCount="1" totalQueryResultCount="1" transactionKey="82b3de57-f07f-4d00-8343-641e239e868f">
  <Facility>
    <CERSID>10215613</CERSID>
    <RegulatorCode>1500</RegulatorCode>
    <Name>ARCO #1</Name>
    <LastSubmittalOn>2014-04-14</LastSubmittalOn>
    <EstablishedOn>2014-04-14</EstablishedOn>
    <Organization>
      <Code>90184921</Code>
      <Name><![CDATA[ARCO EMPIRE]]></Name>
      <Headquarters><![CDATA[Delano, CA]]></Headquarters>
      <FacilityCount>2</FacilityCount>
      <UserCount>1</UserCount>
      <LeadRegulatorCode>9900</LeadRegulatorCode>
      <LastSubmittalOn>2014-04-14</LastSubmittalOn>
      <Origin>2</Origin>
    </Organization>
    <SubmittalElements>
      <FacilityInformation regulatorCode="1500" reportingRequirement="2" />
      <HazardousMaterialsInventory regulatorCode="1500" reportingRequirement="2" />
      <EmergencyResponseTrainingPlans regulatorCode="1500" reportingRequirement="2" />
      <UndergroundStorageTanks regulatorCode="1500" reportingRequirement="1" />
      <OnsiteHazardousWasteTreatmentNotification regulatorCode="1500" reportingRequirement="1" />
      <RecyclableMaterialsReport regulatorCode="1500" reportingRequirement="2" />
      <RemoteWasteConsolidationsAnnualNotification regulatorCode="1500" reportingRequirement="2" />
      <HWTankClosureCertification regulatorCode="1500" reportingRequirement="2" />
      <AbovegroundPetroleumStorageTanks regulatorCode="1500" reportingRequirement="2" />
      <CaliforniaAccidentalReleasePrevention regulatorCode="1500" reportingRequirement="1" />
    </SubmittalElements>
    <FacilityAddress>
      <SiteAddress><![CDATA[3729 N Maple Ave]]></SiteAddress>
      <City><![CDATA[Delano]]></City>
      <ZipCode><![CDATA[93215]]></ZipCode>
    </FacilityAddress>
    <StandardizedAddress>
      <SiteAddress></SiteAddress>
      <City></City>
      <ZipCode></ZipCode>
    </StandardizedAddress>
    <GeographicInformation>
      <CERSPoint>
        <LatitudeMeasure>35.6087900</LatitudeMeasure>
        <LongitudeMeasure>-119.3470100</LongitudeMeasure>
        <HorizontalAccuracyMeasure>300.0000</HorizontalAccuracyMeasure>
        <HorizontalCollectionMethod>101</HorizontalCollectionMethod>
        <GeographicReferencePoint>102</GeographicReferencePoint>
        <HorizontalReferenceDatum>WGS84</HorizontalReferenceDatum>
        <DataCollectionDate>2014-04-14</DataCollectionDate>
      </CERSPoint>
    </GeographicInformation>
  </Facility>
</cers:RegulatorFacilityQuery>
